export const SET_GAME_NAME = 'set_game_name'
export const SET_CURRENT_PAGE ='set_current_page'
export const SET_CUSTOMER = 'set_customer'
export const REMOVE_CUSTOMER = 'remove_customer'
export const SET_CART_ITEMS = 'set_cart_items'
export const REPLACE_CART_ITEMS = 'replace_cart_items'
export const ADD_POST = 'add_post'